import { type ConfigPlan, type PlanValue } from './plan.ts'

export interface EmitOptions {
    /** Additional comment lines placed below the standard generated-file notice, e.g. provenance info like the input path and content hash. */
    banner?: string
    /**
     * Output language. 'ts' (default) emits TypeScript whose config object is checked with `satisfies`; 'js' emits plain JavaScript with byte-identical runtime behavior — for projects that don't use TypeScript, and for consumers that must serve the module without a transform step (the Vite plugin's in-memory module, which Vite's own esbuild transform does not reliably process for virtual ids).
     */
    format?: 'ts' | 'js'
    /**
     * Module specifier the emitted code imports tailwind-merge's API from. Defaults to 'tailwind-merge'. A bundler plugin serving the module virtually has no filesystem location to resolve a bare 'tailwind-merge' from, so it substitutes a specifier of its own package that re-exports tailwind-merge — resolvable from anywhere because the plugin package is the user's direct dependency.
     */
    importSource?: string
}

/**
 * Serializes a plan into the source code of a standalone module exporting `getConfig` and `twMerge`.
 *
 * The whole config is built inside `getConfig` so that nothing is allocated at module evaluation — `createTailwindMerge` invokes the callback on the first `twMerge` call, preserving the library's lazy-init behavior. The module imports only `createTailwindMerge` and `validators` from tailwind-merge, so bundlers tree-shake the default config away.
 *
 * Two measured insights shape the output. Validators are destructured once and referenced as bare identifiers because property accesses like `v.isArbitraryVariable` survive minification while local bindings get mangled. And only the resolved theme scales are shared as consts, emitted as references or spreads (e.g. `['none', ...scaleBlur]`): deduplicating other repetition into consts shrinks the minified size but *grows* the compressed size, since references add entropy where gzip/brotli handled the repetition nearly for free (measured on the vanilla theme: 31,989 / 8,822 / 7,706 bytes minified / gzip / brotli with scale sharing, against 28,492 / 9,364 / 8,197 with every paying repetition hoisted). Sharing array identity across class groups is safe because tailwind-merge never mutates config arrays. Output is deterministic for identical input so the CLI's `--check` mode can diff against the file on disk.
 */
export function emitModule(plan: ConfigPlan, options: EmitOptions = {}): string {
    const format = options.format ?? 'ts'
    const candidates = collectConstantCandidates(plan)

    // Serialize with every scale const available, then emit only the consts actually referenced — directly from the config or transitively from another emitted const; a pruned plan can leave every scale unreferenced.
    const names = new Map([...candidates].map(([canonical, candidate]) => [canonical, candidate.name]))
    const output = serializeAll(plan, candidates, names, format)
    const usedCanonicals = resolveTransitiveUsage(output)
    const { configBody } = output

    const lines: string[] = []

    // Always present, independent of caller-supplied banner lines: readers of the file must be able to tell it is generated and where to regenerate it.
    lines.push('// Generated by @tailwind-merge/configurator. Do not edit manually.')
    if (options.banner) {
        lines.push(options.banner)
    }
    lines.push('')

    // Validators are referenced as bare identifiers instead of `v.name` property accesses: property names survive minification while local bindings get mangled to single characters, and validator references are among the most repeated tokens in the config. A pruned plan can need no validator at all; the import then goes too, or `noUnusedLocals` would reject the emitted TypeScript.
    const usedValidators = collectUsedValidatorNames(plan)
    const importSource = options.importSource ?? 'tailwind-merge'
    const validatorsImport = usedValidators.length > 0 ? ', validators as v' : ''
    lines.push(
        format === 'ts'
            ? `import { createTailwindMerge${validatorsImport}, type Config } from '${importSource}'`
            : `import { createTailwindMerge${validatorsImport} } from '${importSource}'`,
    )
    lines.push('')
    lines.push('/**')
    lines.push(
        ' * Builds the tailwind-merge config for this project. Called lazily on the first `twMerge` call. Can be composed further via `createTailwindMerge(getConfig, ...extensions)`.',
    )
    lines.push(' *')
    lines.push(
        " * The structure mirrors tailwind-merge's default config. The `scale*` consts hold this project's resolved theme scales — each one's comment says which theme namespace it came from — and class groups use them by reference or as spreads. Patterns like `isTshirtSize` come from tailwind-merge's public validators.",
    )
    lines.push(' */')
    lines.push('export const getConfig = () => {')

    if (usedValidators.length > 0) {
        const inline = `${INDENT}const { ${usedValidators.join(', ')} } = v`
        if (inline.length <= MAX_LINE_LENGTH) {
            lines.push(inline)
        } else {
            lines.push(`${INDENT}const {`)
            lines.push(...usedValidators.map((name) => `${INDENT}${INDENT}${name},`))
            lines.push(`${INDENT}} = v`)
        }
        lines.push('')
    }

    const emittedConstants = sortByDependencies(output, usedCanonicals)
    for (const [canonical, body] of emittedConstants) {
        const { name, comment } = candidates.get(canonical)!
        if (comment) {
            lines.push(`${INDENT}/** ${comment} */`)
        }
        lines.push(`${INDENT}const ${name} = ${body}`)
    }
    // Only the consts actually emitted earn the separating blank line — a pruned plan can leave every shared-scale candidate unreferenced.
    if (emittedConstants.length > 0) {
        lines.push('')
    }

    lines.push(...configBody)
    lines.push('}')
    lines.push('')
    lines.push('export const twMerge = createTailwindMerge(getConfig)')
    lines.push('')

    return lines.join('\n')
}

const MAX_LINE_LENGTH = 100
const INDENT = '    '

/** Validator names in first-use order, for the destructuring statement at the top of `getConfig`. */
function collectUsedValidatorNames(plan: ConfigPlan): string[] {
    const names = new Set<string>()

    function visitItems(items: PlanValue[]) {
        for (const item of items) {
            if (item.kind === 'validator') {
                names.add(item.name)
            } else if (item.kind === 'object') {
                for (const [, entryItems] of item.entries) {
                    visitItems(entryItems)
                }
            }
        }
    }

    for (const [, items] of plan.classGroups) {
        visitItems(items)
    }

    return [...names]
}

/** A resolved theme scale emitted as a shared const, referenced or spread wherever a group array contains it. */
interface ConstantCandidate {
    items: PlanValue[]
    /** Item-wise canonical forms, used for run matching. */
    itemCanonicals: string[]
    /** Const name derived from the theme key (e.g. `scaleColor`). */
    name: string
    /** JSDoc text emitted above the const declaration. Stripped by minifiers, so it costs nothing in production bundles. */
    comment: string | null
}

type CandidateMap = Map<string, ConstantCandidate>

interface SerializedOutput {
    configBody: string[]
    constantBodies: Map<string, string>
    /** Canonicals referenced from the config body itself. */
    directUsage: Set<string>
    /** Canonicals referenced from within each candidate's body. */
    usageByConstant: Map<string, Set<string>>
}

/** Gathers the resolved theme scales as shared-const candidates; group arrays contain them verbatim wherever a theme getter was substituted. Theme keys are unique, so the derived names are too. */
function collectConstantCandidates(plan: ConfigPlan): CandidateMap {
    const candidates: CandidateMap = new Map()

    for (const [themeKey, scale] of plan.scales) {
        if (scale.items.length < 2) {
            continue
        }
        const canonical = canonicalArray(scale.items)
        const existing = candidates.get(canonical)
        if (!existing) {
            candidates.set(canonical, {
                items: scale.items,
                itemCanonicals: scale.items.map(canonicalValue),
                name: scaleConstName(themeKey),
                comment: scale.comment,
            })
        } else if (scale.comment !== null) {
            // Two theme scales resolved to identical content and share one const; the comment must mention both origins.
            existing.comment = `${existing.comment ?? ''} ${scale.comment}`.trim()
        }
    }

    return candidates
}

/** `color` → `scaleColor`, `font-weight` → `scaleFontWeight`. The `scale` prefix avoids collisions with destructured validator names. */
function scaleConstName(themeKey: string): string {
    return `scale${themeKey
        .split('-')
        .map((segment) => `${segment[0]?.toUpperCase() ?? ''}${segment.slice(1)}`)
        .join('')}`
}

/**
 * Serializes the config body and every candidate's body with the given name map, recording which candidates each output references so usage can be resolved before final naming.
 */
function serializeAll(
    plan: ConfigPlan,
    candidates: CandidateMap,
    names: Map<string, string>,
    format: 'ts' | 'js',
): SerializedOutput {
    const directUsage = new Set<string>()
    const usageByConstant = new Map<string, Set<string>>()

    const constantBodies = new Map<string, string>()
    for (const [canonical, candidate] of candidates) {
        const usage = new Set<string>()
        constantBodies.set(
            canonical,
            serializeArrayBody(candidate.items, 4, {
                candidates,
                names,
                usage,
                selfCanonical: canonical,
            }),
        )
        usageByConstant.set(canonical, usage)
    }

    const context: SerializeContext = {
        candidates,
        names,
        usage: directUsage,
        selfCanonical: null,
    }

    const configBody: string[] = []
    configBody.push(`${INDENT}return {`)
    configBody.push(`${INDENT}${INDENT}cacheSize: ${plan.cacheSize},`)
    if (plan.prefix !== null) {
        configBody.push(`${INDENT}${INDENT}prefix: ${quote(plan.prefix)},`)
    }
    configBody.push(`${INDENT}${INDENT}theme: {},`)

    configBody.push(`${INDENT}${INDENT}classGroups: {`)
    for (const [classGroupId, items] of plan.classGroups) {
        configBody.push(
            `${INDENT.repeat(3)}${propertyKey(classGroupId)}: ${serializeArray(items, 12, context)},`,
        )
    }
    configBody.push(`${INDENT}${INDENT}},`)

    pushStringRecordMap(configBody, 'conflictingClassGroups', plan.conflictingClassGroups)
    pushStringRecordMap(
        configBody,
        'conflictingClassGroupModifiers',
        plan.conflictingClassGroupModifiers,
    )

    configBody.push(
        `${INDENT}${INDENT}postfixLookupClassGroups: ${serializeStringArray(plan.postfixLookupClassGroups)},`,
    )
    configBody.push(
        `${INDENT}${INDENT}orderSensitiveModifiers: ${serializeStringArray(plan.orderSensitiveModifiers)},`,
    )
    configBody.push(format === 'ts' ? `${INDENT}} satisfies Config<string, never>` : `${INDENT}}`)

    return { configBody, constantBodies, directUsage, usageByConstant }
}

/** Usage is transitive: a const referenced only from another used const's body still has to be emitted. */
function resolveTransitiveUsage(output: SerializedOutput): Set<string> {
    const used = new Set<string>(output.directUsage)
    let changed = true

    while (changed) {
        changed = false
        for (const canonical of used) {
            for (const referenced of output.usageByConstant.get(canonical) ?? []) {
                if (!used.has(referenced)) {
                    used.add(referenced)
                    changed = true
                }
            }
        }
    }

    return used
}

/** Orders the used consts so that every reference points to an already-declared name, using the exact usage sets recorded during serialization. Containment makes cycles impossible. */
function sortByDependencies(output: SerializedOutput, used: Set<string>): [string, string][] {
    const remaining = new Map(
        [...output.constantBodies].filter(([canonical]) => used.has(canonical)),
    )
    const declared = new Set<string>()
    const sorted: [string, string][] = []

    while (remaining.size > 0) {
        let progressed = false

        for (const [canonical, body] of remaining) {
            const dependencies = [...(output.usageByConstant.get(canonical) ?? [])].filter(
                (dependency) => used.has(dependency) && dependency !== canonical,
            )
            if (dependencies.every((dependency) => declared.has(dependency))) {
                declared.add(canonical)
                sorted.push([canonical, body])
                remaining.delete(canonical)
                progressed = true
            }
        }

        if (!progressed) {
            throw new Error('Cyclic references between generated consts, this is a bug in emit.ts')
        }
    }

    return sorted
}

interface SerializeContext {
    candidates: CandidateMap
    names: Map<string, string>
    usage: Set<string>
    /** Canonical of the candidate currently being defined, which must not reference itself. */
    selfCanonical: string | null
}

function serializeArray(items: PlanValue[], indent: number, context: SerializeContext): string {
    const canonical = canonicalArray(items)
    if (canonical !== context.selfCanonical) {
        const name = context.names.get(canonical)
        if (name) {
            context.usage.add(canonical)
            return name
        }
    }
    return serializeArrayBody(items, indent, context)
}

function serializeArrayBody(
    items: PlanValue[],
    indent: number,
    context: SerializeContext,
): string {
    const itemCanonicals = items.map(canonicalValue)
    const parts: string[] = []

    let index = 0
    while (index < items.length) {
        const run = findLongestRun(items, itemCanonicals, index, context)
        if (run) {
            parts.push(`...${run.name}`)
            context.usage.add(run.canonical)
            index += run.length
        } else {
            parts.push(serializeValue(items[index]!, indent + 4, context))
            index += 1
        }
    }

    const inline = `[${parts.join(', ')}]`
    if (indent + inline.length <= MAX_LINE_LENGTH && !inline.includes('\n')) {
        return inline
    }

    const itemIndent = INDENT.repeat(indent / 4 + 1)
    const closingIndent = INDENT.repeat(indent / 4)
    return `[\n${parts.map((part) => `${itemIndent}${part},`).join('\n')}\n${closingIndent}]`
}

/** Finds the longest candidate array matching the items starting at `start`, to be emitted as a spread. Skips the candidate currently being defined and full-array matches (those are handled as plain references). */
function findLongestRun(
    items: PlanValue[],
    itemCanonicals: string[],
    start: number,
    context: SerializeContext,
): { name: string; canonical: string; length: number } | null {
    let best: { name: string; canonical: string; length: number } | null = null

    for (const [canonical, candidate] of context.candidates) {
        if (canonical === context.selfCanonical) {
            continue
        }
        const length = candidate.itemCanonicals.length
        if (
            length < 2 ||
            (start === 0 && length === items.length) ||
            start + length > items.length ||
            (best && length <= best.length)
        ) {
            continue
        }
        const name = context.names.get(canonical)
        if (!name) {
            continue
        }

        let matches = true
        for (let offset = 0; offset < length; offset++) {
            if (itemCanonicals[start + offset] !== candidate.itemCanonicals[offset]) {
                matches = false
                break
            }
        }
        if (matches) {
            best = { name, canonical, length }
        }
    }

    return best
}

function serializeValue(value: PlanValue, indent: number, context: SerializeContext): string {
    if (value.kind === 'class') {
        return quote(value.value)
    }
    if (value.kind === 'validator') {
        return value.name
    }
    return serializeObjectBody(value, indent, context)
}

function serializeObjectBody(
    value: Extract<PlanValue, { kind: 'object' }>,
    indent: number,
    context: SerializeContext,
): string {
    const entryParts = value.entries.map(
        ([key, items]) => `${propertyKey(key)}: ${serializeArray(items, indent + 4, context)}`,
    )
    const inline = `{ ${entryParts.join(', ')} }`

    if (indent + inline.length <= MAX_LINE_LENGTH && !inline.includes('\n')) {
        return inline
    }

    const entryIndent = INDENT.repeat(indent / 4 + 1)
    const closingIndent = INDENT.repeat(indent / 4)
    return `{\n${entryParts.map((part) => `${entryIndent}${part},`).join('\n')}\n${closingIndent}}`
}

/**
 * Canonical string form used as identity for scale references and run matching: fully inlined, ignoring shared consts and line breaks, so identical content always produces identical keys. Cached by node identity since plans reuse instances for repeated scales.
 */
function canonicalArray(items: PlanValue[]): string {
    let canonical = canonicalArrayCache.get(items)
    if (!canonical) {
        canonical = `[${items.map(canonicalValue).join(', ')}]`
        canonicalArrayCache.set(items, canonical)
    }
    return canonical
}

function canonicalValue(value: PlanValue): string {
    if (value.kind === 'class') {
        return quote(value.value)
    }
    if (value.kind === 'validator') {
        return `v.${value.name}`
    }
    let canonical = canonicalObjectCache.get(value)
    if (!canonical) {
        canonical = `{ ${value.entries
            .map(([key, items]) => `${propertyKey(key)}: ${canonicalArray(items)}`)
            .join(', ')} }`
        canonicalObjectCache.set(value, canonical)
    }
    return canonical
}

const canonicalArrayCache = new WeakMap<PlanValue[], string>()
const canonicalObjectCache = new WeakMap<Extract<PlanValue, { kind: 'object' }>, string>()

function pushStringRecordMap(lines: string[], property: string, map: Map<string, string[]>) {
    if (map.size === 0) {
        // Possible after pruning leaves no conflict edges between the kept groups.
        lines.push(`${INDENT}${INDENT}${property}: {},`)
        return
    }
    lines.push(`${INDENT}${INDENT}${property}: {`)
    for (const [key, values] of map) {
        lines.push(`${INDENT.repeat(3)}${propertyKey(key)}: ${serializeStringArray(values)},`)
    }
    lines.push(`${INDENT}${INDENT}},`)
}

function serializeStringArray(values: readonly string[]): string {
    return `[${values.map(quote).join(', ')}]`
}

/** Object literals treat __proto__ as a prototype setter even when quoted; computed syntax preserves the theme entry as an own property. */
function propertyKey(key: string): string {
    if (key === '__proto__') {
        return `[${quote(key)}]`
    }
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : quote(key)
}

function quote(value: string): string {
    return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
}
