import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import { afterAll, beforeAll, describe, expect, test } from 'vitest'

import { runCli } from '../src/run-cli'

import { fixtureBase } from './fixture-utils'

describe('CLI with --check mode', () => {
    let directory: string
    let inputPath: string
    let outputPath: string

    beforeAll(async () => {
        // The temp directory lives inside tests/ (not the OS temp dir) because `@import 'tailwindcss'` resolves relative to the input file, and only from here does the upward walk reach the configurator's node_modules.
        directory = await mkdtemp(join(fixtureBase, '.tmp-cli-'))
        inputPath = join(directory, 'app.css')
        outputPath = join(directory, 'tw-merge.generated.ts')
    })

    afterAll(async () => {
        await rm(directory, { recursive: true, force: true })
    })

    test('generates, reports up-to-date, and detects staleness', async () => {
        await writeFile(inputPath, "@import 'tailwindcss';\n@theme { --color-brand-500: #33f; }\n")

        expect(await runCli(['--input', inputPath, '--output', outputPath])).toBe(0)
        const generated = await readFile(outputPath, 'utf8')
        expect(generated).toContain('Generated by @tailwind-merge/configurator')
        expect(generated).toContain('// Source: app.css (sha256 ')

        expect(await runCli(['--input', inputPath, '--output', outputPath, '--check'])).toBe(0)

        await writeFile(
            inputPath,
            "@import 'tailwindcss';\n@theme { --color-brand-500: #44f; --color-brand-900: #113; }\n",
        )
        expect(await runCli(['--input', inputPath, '--output', outputPath, '--check'])).toBe(1)

        expect(await runCli(['--input', inputPath, '--output', outputPath])).toBe(0)
        expect(await runCli(['--input', inputPath, '--output', outputPath, '--check'])).toBe(0)
    })

    test('fails the check when the output file is missing', async () => {
        const missingPath = join(directory, 'missing.generated.ts')
        expect(await runCli(['--input', inputPath, '--output', missingPath, '--check'])).toBe(1)
    })

    test('fails with usage message when arguments are missing', async () => {
        expect(await runCli([])).toBe(1)
        expect(await runCli(['--input', inputPath])).toBe(1)
        expect(await runCli(['--input', inputPath, '--output', outputPath, '--format', 'tsx'])).toBe(
            1,
        )
    })

    test('a .js output emits JavaScript, and --format overrides the inference', async () => {
        await writeFile(inputPath, "@import 'tailwindcss';\n@theme { --color-brand-500: #33f; }\n")

        const jsPath = join(directory, 'tw-merge.generated.js')
        expect(await runCli(['--input', inputPath, '--output', jsPath])).toBe(0)
        const jsCode = await readFile(jsPath, 'utf8')
        expect(jsCode).not.toContain('satisfies')
        expect(jsCode).not.toContain('type Config')
        // --check compares against the same inferred format, so a js output stays reproducible.
        expect(await runCli(['--input', inputPath, '--output', jsPath, '--check'])).toBe(0)

        const forcedPath = join(directory, 'tw-merge.forced.ts')
        expect(
            await runCli(['--input', inputPath, '--output', forcedPath, '--format', 'js']),
        ).toBe(0)
        expect(await readFile(forcedPath, 'utf8')).not.toContain('satisfies')
    })
})
