name: 'metrics-report-action'
author: 'Dany Castillo'
description: 'Generates a report about changes in important metrics related to tailwind-merge'
inputs:
    comment-body-path:
        description: 'Path to write the generated metrics report comment body'
        required: true
runs:
    using: 'node24'
    main: 'src/main.mjs'
