// Generated by @tailwind-merge/configurator. Do not edit manually.

import { createTailwindMerge, validators as v } from 'tailwind-merge'

/**
 * Builds the tailwind-merge config for this project. Called lazily on the first `twMerge` call. Can be composed further via `createTailwindMerge(getConfig, ...extensions)`.
 *
 * The structure mirrors tailwind-merge's default config. The `scale*` consts hold this project's resolved theme scales — each one's comment says which theme namespace it came from — and class groups use them by reference or as spreads. Patterns like `isTshirtSize` come from tailwind-merge's public validators.
 */
export const getConfig = () => {
    const { isNumber } = v

    return {
        cacheSize: 500,
        theme: {},
        classGroups: {
            display: ['flex'],
            p: [{ p: [isNumber] }],
            'text-color': [{ text: [{ red: [isNumber] }] }],
            'text-decoration': ['underline'],
        },
        conflictingClassGroups: {},
        conflictingClassGroupModifiers: {},
        postfixLookupClassGroups: [],
        orderSensitiveModifiers: ['*', '**', 'after', 'backdrop', 'before', 'details-content', 'file', 'first-letter', 'first-line', 'marker', 'placeholder', 'selection'],
    }
}

export const twMerge = createTailwindMerge(getConfig)
