// This file can only be executed with zx. More info: https://github.com/google/zx

// @ts-check

import 'zx/globals'

import packageJson from '../package.json' with { type: 'json' }

$.verbose = true

const GENERATED_SECTION_MARKER_START = '<!-- tailwind-merge-docs:start -->'
const GENERATED_SECTION_MARKER_END = '<!-- tailwind-merge-docs:end -->'

updateReadmes()

/**
 * Generates the published READMEs from docs/README.md: the package README.md that ships to npm (the whole file) and the generated section between the markers in the repo-level README.md, which inlines the same content because the library is what most repo visitors come for. Runs as the package's `version` lifecycle script, so both stay in sync with each release and carry links pinned to the release tag.
 */
async function updateReadmes() {
    const PACKAGE_ROOT_PATH = `${__dirname}/..`
    const REPO_ROOT_PATH = `${PACKAGE_ROOT_PATH}/../..`
    const README_PATH = `${PACKAGE_ROOT_PATH}/README.md`
    const REPO_README_PATH = `${REPO_ROOT_PATH}/README.md`
    const DOCS_OVERVIEW_PATH = `${PACKAGE_ROOT_PATH}/docs/README.md`

    const [currentReadmeContent, currentRepoReadmeContent, currentDocsOverviewContent] =
        await Promise.all([
            fs.readFile(README_PATH, { encoding: 'utf-8' }),
            fs.readFile(REPO_README_PATH, { encoding: 'utf-8' }),
            fs.readFile(DOCS_OVERVIEW_PATH, { encoding: 'utf-8' }),
        ])

    const staticallyLinkedContent = applyStaticLinks(currentDocsOverviewContent)

    const nextReadmeContent = addAutoGeneratedInfoComment(staticallyLinkedContent)
    const nextRepoReadmeContent = replaceGeneratedSection(
        currentRepoReadmeContent,
        staticallyLinkedContent,
    )

    await Promise.all([
        nextReadmeContent === currentReadmeContent
            ? undefined
            : fs.writeFile(README_PATH, nextReadmeContent),
        nextRepoReadmeContent === currentRepoReadmeContent
            ? undefined
            : fs.writeFile(REPO_README_PATH, nextRepoReadmeContent),
    ])

    await $`git add ${README_PATH} ${REPO_README_PATH}`
}

/**
 * Replaces the relative links in the docs overview with absolute ones pinned to the release tag, so the generated READMEs keep working from npm and from old revisions.
 *
 * @param {string} docsOverviewContent
 * @returns {string}
 */
function applyStaticLinks(docsOverviewContent) {
    const version = getVersion()

    const nextDocsOverviewContent = docsOverviewContent
        .replace(
            /(["'`(])\.\.\/(assets\/[^\s]+)(["'`)])/g,
            `$1https://github.com/dcastil/tailwind-merge/raw/${version}/packages/tailwind-merge/$2$3`,
        )
        .replace(
            /(["'`(])\.\/([^\s]+\.md)(["'`)])/g,
            `$1https://github.com/dcastil/tailwind-merge/blob/${version}/packages/tailwind-merge/docs/$2$3`,
        )

    if (nextDocsOverviewContent === docsOverviewContent) {
        throw Error(`${chalk.red('[ERROR]')} Did not update anything in docs overview file.`)
    }

    return nextDocsOverviewContent
}

function getVersion() {
    const gitRefVersionRegex = /^\d+.\d+.\d+-[^.]+\.(?<gitRef>[\da-f]+)$/

    // Release tags are namespaced per package (`tailwind-merge@<version>`) since the monorepo migration; SHA-suffixed dev versions link to the commit itself instead.
    return (
        packageJson.version.match(gitRefVersionRegex)?.groups?.gitRef ||
        `${packageJson.name}@${packageJson.version}`
    )
}

/**
 * @param {string} content
 * @returns {string}
 */
function addAutoGeneratedInfoComment(content) {
    return (
        '<!-- This file is autogenerated. If you want to change this content, please do the changes in `./docs/README.md` instead. -->\n\n' +
        content
    )
}

/**
 * Replaces the content between the generated-section markers in the repo-level README, failing loudly when the markers are missing so a reworked repo README cannot silently detach from the release flow.
 *
 * @param {string} repoReadmeContent
 * @param {string} generatedContent
 * @returns {string}
 */
function replaceGeneratedSection(repoReadmeContent, generatedContent) {
    const startIndex = repoReadmeContent.indexOf(GENERATED_SECTION_MARKER_START)
    const endIndex = repoReadmeContent.indexOf(GENERATED_SECTION_MARKER_END)

    if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
        throw Error(
            `${chalk.red('[ERROR]')} Did not find the generated section markers in the repo README.`,
        )
    }

    return (
        repoReadmeContent.slice(0, startIndex + GENERATED_SECTION_MARKER_START.length) +
        '\n\n<!-- This section is autogenerated. If you want to change this content, please do the changes in `packages/tailwind-merge/docs/README.md` instead. -->\n\n' +
        generatedContent.trim() +
        '\n\n' +
        repoReadmeContent.slice(endIndex)
    )
}
