export { twMerge } from './tailwind-merge'
export { getDefaultConfig } from './default-config'
export { extendTailwindMerge } from './extend-tailwind-merge'
export { createTailwindMerge } from './create-tailwind-merge'
export type { Config } from './types'
export * as validators from './validators'
export { mergeConfigs } from './merge-configs'
