name: Draft Release

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    update_release_draft:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: read
        steps:
            - uses: release-drafter/release-drafter@v7
              with:
                  token: ${{ github.token }}

    auto_label:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: release-drafter/release-drafter/autolabeler@v7
              with:
                  token: ${{ github.token }}
