name: Test

on:
    push:
        branches: ['**']
    pull_request:
        branches: ['**']

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false
            - name: Use Node.js 24
              uses: actions/setup-node@v6
              with:
                  node-version: 24.18.0
            - run: corepack enable
            - run: pnpm install --frozen-lockfile
            - run: pnpm lint
            - run: pnpm test:types
            - run: pnpm test
            - run: pnpm build
            - uses: actions/upload-artifact@v7
              with:
                  name: build-output
                  path: dist
                  if-no-files-found: error
            - run: pnpm test:exports
